Add files via upload
DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again pull request #1
Opened 2023-08-23 18:39 UTC by Dybbuk1

2023-08-23 19:48 UTC, dazedanon requested changes
Can you test lines with single quotes and make sure they work? I'm pretty sure they will conflict with the surrounding ones.

2023-08-23 19:48 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "'I'm starting to understand the method little by little'"
I don't think this is going to work because the `'` in `I'm` conflicts with the surrounding single quotes. Have you tested this one?

2023-08-23 19:48 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "'But I don't want anyone else but Masamune.'"
Same here

2023-08-23 19:48 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "'I wonder if he doesn't mind getting a blowjob'"
Same here

2023-08-23 19:48 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "'It might be... and addictive taste'"
an addictive taste

2023-08-23 19:48 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "'I don't feel good about it.'"
Same here

2023-08-23 19:48 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "'I can't wait to have sex with you.'"
Same here

2023-08-23 19:50 UTC, Dybbuk1 commented
Currently doing a run with the file. I will check if I have any issues.
________________________________
From: dazedanon ***@***.***>
Sent: 23 August 2023 20:48
To: DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again ***@***.***>
Cc: Dybbuk1 ***@***.***>; Author ***@***.***>
Subject: Re: [DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again] Add files via upload (PR #1)


@dazedanon requested changes on this pull request.

Can you test lines with single quotes and make sure they work? I'm pretty sure they will conflict with the surrounding ones.

________________________________

In www/data/CommonEvents.json<https://github.com/DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again/pull/1#discussion_r1303470855>:

> @@ -10372,7 +10372,7 @@
                     43,
                     0,
                     4,
-                    "'Im starting to understand the method little by little'"
+                    "'I'm starting to understand the method little by little'"


I don't think this is going to work because the ' in I'm conflicts with the surrounding single quotes. Have you tested this one?

________________________________

In www/data/CommonEvents.json<https://github.com/DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again/pull/1#discussion_r1303471104>:

> @@ -10383,7 +10383,7 @@
                     44,
                     0,
                     4,
-                    "'でも正宗君の以外はいや'"
+                    "'But I don't want anyone else but Masamune.'"


Same here

________________________________

In www/data/CommonEvents.json<https://github.com/DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again/pull/1#discussion_r1303471152>:

> @@ -10415,7 +10415,7 @@
                     43,
                     0,
                     4,
-                    "'I wonder if she doesnt mind giving a blowjob'"
+                    "'I wonder if he doesn't mind getting a blowjob'"


Same here

________________________________

In www/data/CommonEvents.json<https://github.com/DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again/pull/1#discussion_r1303471538>:

> @@ -10426,7 +10426,7 @@
                     44,
                     0,
                     4,
-                    "'クセになる味……かも'"
+                    "'It might be... and addictive taste'"


an addictive taste

________________________________

In www/data/CommonEvents.json<https://github.com/DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again/pull/1#discussion_r1303471823>:

> @@ -10828,7 +10828,7 @@
                     50,
                     0,
                     4,
-                    "'莩证沥瑜胜欷胜い'"
+                    "'I don't feel good about it.'"


Same here

________________________________

In www/data/CommonEvents.json<https://github.com/DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again/pull/1#discussion_r1303471994>:

> @@ -10914,7 +10914,7 @@
                     50,
                     0,
                     4,
-                    "'早くセックスしたい'"
+                    "'I can't wait to have sex with you.'"


Same here

―
Reply to this email directly, view it on GitHub<https://github.com/DazedMTL/Amelie-Blanchet-Falls-Over-and-Over-Again/pull/1#pullrequestreview-1592302259>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BBDCGRRZEKXRH6ZKRAT42I3XWZNB5ANCNFSM6AAAAAA334RGSY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-23 20:43 UTC, Dybbuk1 commented
> Can you test lines with single quotes and make sure they work? I'm pretty sure they will conflict with the surrounding ones.



> Can you test lines with single quotes and make sure they work? I'm pretty sure they will conflict with the surrounding ones.

I have just had a syntax error while playing. I am removing the ' and try again, and I will let you know.

2023-08-23 21:21 UTC, Dybbuk1 commented
I must have done something else while tinkering on the common events, as I have reverted those lines with the single quotes and I kept with the syntax error. Loaded the patch from the repository and it works fine, so I will translate those lines carefully and see if any of them cause the syntax error again. I have a save just prior to it.

2023-08-24 17:53 UTC, dazedanon commented
@Dybbuk1 Using your changes as reference I've translated the rest of those vars. Pull the latest when you can.

2023-08-27 18:51 UTC, dazedanon commented
Closing this for now. Feel free to open another PR if you fix the changes.

2023-08-27 18:51 UTC, closed without merging